### ISSUE TITLE
Mobile bugs

### ISSUE THREAD

**Issue by losowsky** [coralproject/experiment-playground#103]
• Edit comment appears on all the comments, not just yours
• Edit Comment text is HUGE 
![file_000](https://cloud.githubusercontent.com/assets/10014755/18487615/f040de98-79c3-11e6-87f6-9e04a808ad1f.png)
• Got It on opening message is too close to the text
![file_000 1](https://cloud.githubusercontent.com/assets/10014755/18487634/002c883e-79c4-11e6-83c6-a45e1abbc1be.png)
• You can swipe right on my iPhone 6 in Safari and it moves the content beyond the width of the top bar
![file_000 2](https://cloud.githubusercontent.com/assets/10014755/18487649/0ada2f52-79c4-11e6-89f4-07477c699efd.png)
• Having some Comment Count not appearing issues on mobile at this url [http://web03_stg.coralproject.net/playground#%7B%22badges%22%3Atrue%2C%22replies%22%3Atrue%2C%22staffpicks%22%3Atrue%2C%22profilepictures%22%3Atrue%2C%22emoji%22%3Atrue%2C%22hiddenbydefault%22%3Atrue%2C%22commentcount%22%3Atrue%7D](url)
• Hide comments text overlapping 
![file_000 3](https://cloud.githubusercontent.com/assets/10014755/18487900/14421298-79c5-11e6-85bc-535b3730b694.png)

**Comment by davidgljay** [comment]
All issues dealt with except the comment count (can't reproduce) and the swiping to the left. (The code exists to fix this and isn't working, though the same reactive CSS works elsewhere in the application. This appears to be a bug with react-mdl. I'm investigating and filing an issue or PR with them, but not before ONA.
