### ISSUE TITLE
Modal closing issue on iphone

### ISSUE THREAD

**Issue by losowsky** [coralproject/experiment-playground#112]
In Safari, when I open the information modals on each feature, the "Got It" button doesn't seem to work. Also on long modals, it's hidden below the bottom of the screen with no scrolling.

**Comment by davidgljay** [comment]
I'm investigating the "Got it" issue, unfortunately the idea that dialogs aren't scrollable is pretty fundamental to how they're implemented. We could hack together different functionality (making modals scroll with the page, though this departs from the usual design standard), or consider a different way to display this information. Either is a decent-sized project. Let's call it a "3" in our estimation parlance.

**Comment by davidgljay** [comment]
Never mind, found an elegant styling fix! Closing.
