### ISSUE TITLE
Rich text bug

### ISSUE THREAD

**Issue by losowsky** [coralproject/experiment-playground#117]
If I click Bold or Italic, it doesn't then stick when I start typing. I have to highlight already typed text and click it to make it work. Also not sure what the quote marks do - can't get it working. Remove it?

**Comment by davidgljay** [comment]
This bug has been resolved with the emoji bug. The quote marks and link button currently don't do anything. Should I remove them?

@losowsky

**Comment by losowsky** [comment]
Yep. And the emoji bug is fixed, but this is still current for me.

**Comment by losowsky** [comment]
![richtextbug](https://cloud.githubusercontent.com/assets/10014755/18648069/f967c618-7e86-11e6-8e69-ca5b8986d474.gif)
