### ISSUE TITLE
Important mobile bugs on iPhone 6 / iOS9

### ISSUE THREAD

**Issue by losowsky** [coralproject/experiment-playground#119]
• When I click on the hamburger menu, this happens:
![img_9296](https://cloud.githubusercontent.com/assets/10014755/18961049/b614f0f6-8639-11e6-9992-fb4fbe39883e.PNG)

• When an info modal is larger than the screen, the scroll doesn't work to get to "Got it" to close the dialog box. So there's no way to close large dialog boxes. You have to reload to get back to the page.
![img_9338](https://cloud.githubusercontent.com/assets/10014755/18961275/6f493bae-863a-11e6-921f-44c7741fb253.PNG)

**Comment by davidgljay** [comment]
There are addressed in PR https://github.com/coralproject/comments-lab/pull/121

@losowsky, I'm not sure the best way to test these before pushing them live...

**Comment by okbel** [comment]
Looks good! Tested with Xcode

<img width="299" alt="screen shot 2016-10-13 at 3 18 09 pm" src="https://cloud.githubusercontent.com/assets/1401559/19361264/60022a38-9158-11e6-8a90-d88f7f63ff5b.png">
